/**
 * Migration: upserts all gear items that were missing from rs3_gear_items
 * or had no icon_url set. Safe to re-run (INSERT OR REPLACE is idempotent).
 *
 * Run: node server/scripts/addMissingGearIcons.js
 *      (from the project root, or as written it resolves paths itself)
 *
 * Dragon 2H sword (id: dragon_2h_sword) is already seeded — included here
 * only to patch its icon_url if it is still NULL.
 *
 * Image URL convention: https://runescape.wiki/images/<Filename>.png
 * All filenames were verified against runescape.wiki (May 2026).
 */

const path = require('path');
process.chdir(path.join(__dirname, '..'));
const db = require('../database');

// Base wiki image URL helper
const img = filename => `https://runescape.wiki/images/${filename}`;

// Simple wiki URL helper (spaces → underscores)
const wikiUrl = name => `https://runescape.wiki/w/${name.replace(/ /g, '_')}`;

function upsertItem(item) {
  db.prepare(`INSERT OR REPLACE INTO rs3_gear_items
    (id, name, tier, style, slot, is_power_armour, stats, acquisition_source,
     wiki_url, icon_url, untradeable, requirements_json)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`)
  .run(
    item.id,
    item.name,
    item.tier  ?? 0,
    item.style ?? 'all',
    item.slot,
    item.is_power_armour ?? 1,
    '{}',
    item.acquisition_source ?? 'drop',
    item.wiki_url ?? null,
    item.icon_url,
    item.untradeable ?? 0,
    JSON.stringify(item.requirements_json ?? {})
  );
}

// ── VOID requirements (shared across all Void Knight pieces) ─────────────────
const VOID = { Attack: 42, Strength: 42, Defence: 42, Constitution: 42, Ranged: 42, Magic: 42, Prayer: 22 };

const ITEMS = [

  // ══════════════════════════════════════════════════════════════════════════
  // NECK
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'amulet_of_strength',
    name: 'Amulet of strength',
    tier: 0, style: 'melee', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'ge',
    wiki_url: wikiUrl('Amulet of strength'),
    icon_url: img('Amulet_of_strength.png'),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Created from Amulet of fury + blood necklace shard — permanently untradeable
    id: 'blood_amulet_of_fury',
    name: 'Blood amulet of fury',
    tier: 70, style: 'all', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Blood amulet of fury'),
    icon_url: img('Blood_amulet_of_fury.png'),
    untradeable: 1,
    requirements_json: {},
  },
  {
    id: 'blood_necklace',
    name: 'Blood necklace',
    tier: 70, style: 'all', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Blood necklace'),
    icon_url: img('Blood_necklace.png'),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Permanently untradeable once equipped; tradeable when new — treated as tradeable
    id: 'farsight_sniper_necklace',
    name: 'Farsight sniper necklace',
    tier: 0, style: 'ranged', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Farsight sniper necklace'),
    icon_url: img('Farsight_sniper_necklace.png'),
    untradeable: 1, // wiki says "Tradeable: No"
    requirements_json: {},
  },
  {
    // Essence of Finality (melee variant) — same image as the base amulet
    id: 'essence_of_finality_melee',
    name: 'Essence of Finality (melee)',
    tier: 95, style: 'melee', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Essence of Finality amulet'),
    icon_url: img('Essence_of_Finality_amulet.png'),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Essence of Finality (necromancy variant) — same image
    id: 'essence_of_finality_necromancy',
    name: 'Essence of Finality (necromancy)',
    tier: 95, style: 'necromancy', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Essence of Finality amulet'),
    icon_url: img('Essence_of_Finality_amulet.png'),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Plain Essence of Finality (used in hybrid/general contexts) — same image
    id: 'essence_of_finality',
    name: 'Essence of Finality',
    tier: 95, style: 'all', slot: 'neck',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Essence of Finality amulet'),
    icon_url: img('Essence_of_Finality_amulet.png'),
    untradeable: 0,
    requirements_json: {},
  },

  // ══════════════════════════════════════════════════════════════════════════
  // HEAD
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'anima_core_helm_of_seren',
    name: 'Anima core helm of Seren',
    tier: 80, style: 'magic', slot: 'head',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core helm of Seren'),
    icon_url: img('Anima_core_helm_of_Seren.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'anima_core_helm_of_zamorak',
    name: 'Anima core helm of Zamorak',
    tier: 80, style: 'ranged', slot: 'head',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core helm of Zamorak'),
    icon_url: img('Anima_core_helm_of_Zamorak.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'anima_core_helm_of_zaros',
    name: 'Anima core helm of Zaros',
    tier: 80, style: 'melee', slot: 'head',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core helm of Zaros'),
    icon_url: img('Anima_core_helm_of_Zaros.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    // Untradeable — made via slayer reward shop (Smoking Kills quest)
    id: 'corrupted_slayer_helmet',
    name: 'Corrupted slayer helmet',
    tier: 70, style: 'all', slot: 'head',
    is_power_armour: 1,
    acquisition_source: 'slayer',
    wiki_url: wikiUrl('Corrupted slayer helmet'),
    icon_url: img('Corrupted_slayer_helmet.png'),
    untradeable: 1,
    requirements_json: { Slayer: 55 },
  },
  {
    id: 'dragon_full_helm',
    name: 'Dragon full helm',
    tier: 60, style: 'melee', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Dragon full helm'),
    icon_url: img('Dragon_full_helm.png'),
    untradeable: 0,
    requirements_json: { Defence: 60 },
  },
  {
    id: 'rune_full_helm',
    name: 'Rune full helm',
    tier: 50, style: 'melee', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'ge',
    wiki_url: wikiUrl('Rune full helm'),
    icon_url: img('Rune_full_helm.png'),
    untradeable: 0,
    requirements_json: { Defence: 50 },
  },
  {
    // Untradeable — upgraded slayer helmet
    id: 'slayer_helmet_i',
    name: 'Slayer helmet (i)',
    tier: 70, style: 'all', slot: 'head',
    is_power_armour: 1,
    acquisition_source: 'slayer',
    wiki_url: wikiUrl('Slayer helmet (i)'),
    icon_url: img('Slayer_helmet_(i).png'),
    untradeable: 1,
    requirements_json: { Slayer: 55 },
  },
  {
    // Untradeable — Void Knight equipment from Pest Control
    id: 'void_melee_helm',
    name: 'Void melee helm',
    tier: 42, style: 'melee', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Void melee helm'),
    icon_url: img('Void_melee_helm.png'),
    untradeable: 1,
    requirements_json: VOID,
  },
  {
    // Untradeable — Void Knight equipment from Pest Control
    id: 'void_ranger_helm',
    name: 'Void ranger helm',
    tier: 42, style: 'ranged', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Void ranger helm'),
    icon_url: img('Void_ranger_helm.png'),
    untradeable: 1,
    requirements_json: VOID,
  },
  {
    // Tradeable — GE item
    id: 'crown_of_the_first_necromancer',
    name: 'Crown of the First Necromancer',
    tier: 95, style: 'necromancy', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Crown of the First Necromancer'),
    icon_url: img('Crown_of_the_First_Necromancer.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 95 },
  },
  {
    id: 'deathwarden_hood_t70',
    name: 'Deathwarden hood (T70)',
    tier: 70, style: 'necromancy', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathwarden_hood_(tier_70)',
    icon_url: img('Deathwarden_hood_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70, Defence: 70 },
  },
  {
    id: 'deathwarden_hood_t80',
    name: 'Deathwarden hood (T80)',
    tier: 80, style: 'necromancy', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathwarden_hood_(tier_80)',
    icon_url: img('Deathwarden_hood_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80, Defence: 80 },
  },
  {
    // Wiki says untradeable; the T90 nexus is a standalone item (not just a hood reskin)
    id: 'deathwarden_nexus_t90',
    name: 'Deathwarden nexus (T90)',
    tier: 90, style: 'necromancy', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathwarden_nexus',
    icon_url: img('Deathwarden_nexus.png'),
    untradeable: 1, // wiki confirms "not tradeable"
    requirements_json: { Necromancy: 90, Defence: 90 },
  },
  {
    id: 'cryptbloom_helm',
    name: 'Cryptbloom helm',
    tier: 90, style: 'necromancy', slot: 'head',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Cryptbloom helm'),
    icon_url: img('Cryptbloom_helm.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90, Defence: 90 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BODY
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'anima_core_body_of_seren',
    name: 'Anima core body of Seren',
    tier: 80, style: 'magic', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core body of Seren'),
    icon_url: img('Anima_core_body_of_Seren.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'anima_core_body_of_zamorak',
    name: 'Anima core body of Zamorak',
    tier: 80, style: 'ranged', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core body of Zamorak'),
    icon_url: img('Anima_core_body_of_Zamorak.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'anima_core_body_of_zaros',
    name: 'Anima core body of Zaros',
    tier: 80, style: 'melee', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core body of Zaros'),
    icon_url: img('Anima_core_body_of_Zaros.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    // Untradeable — Barbarian Assault reward
    id: 'fighter_torso',
    name: 'Fighter torso',
    tier: 65, style: 'melee', slot: 'body',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Fighter torso'),
    icon_url: img('Fighter_torso.png'),
    untradeable: 1,
    requirements_json: { Defence: 40, Strength: 50 },
  },
  {
    id: 'rune_platebody',
    name: 'Rune platebody',
    tier: 50, style: 'melee', slot: 'body',
    is_power_armour: 0,
    acquisition_source: 'ge',
    wiki_url: wikiUrl('Rune platebody'),
    icon_url: img('Rune_platebody.png'),
    untradeable: 0,
    requirements_json: { Defence: 50 },
  },
  {
    // Untradeable — Void Knight equipment
    id: 'void_ranger_top',
    name: 'Void ranger top',
    tier: 42, style: 'ranged', slot: 'body',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Void ranger top'),
    icon_url: img('Void_ranger_top.png'),
    untradeable: 1,
    requirements_json: VOID,
  },
  {
    id: 'deathdealer_robe_top_t70',
    name: 'Deathdealer robe top (T70)',
    tier: 70, style: 'necromancy', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_robe_top_(tier_70)',
    icon_url: img('Deathdealer_robe_top_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70, Defence: 70 },
  },
  {
    id: 'deathdealer_robe_top_t80',
    name: 'Deathdealer robe top (T80)',
    tier: 80, style: 'necromancy', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_robe_top_(tier_80)',
    icon_url: img('Deathdealer_robe_top_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80, Defence: 80 },
  },
  {
    id: 'cryptbloom_top',
    name: 'Cryptbloom top',
    tier: 90, style: 'necromancy', slot: 'body',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Cryptbloom top'),
    icon_url: img('Cryptbloom_top.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90, Defence: 90 },
  },
  {
    id: 'robe_top_of_the_first_necromancer',
    name: 'Robe top of the First Necromancer',
    tier: 95, style: 'necromancy', slot: 'body',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Robe top of the First Necromancer'),
    icon_url: img('Robe_top_of_the_First_Necromancer.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 95 },
  },
  {
    // T92 hybrid melee; tradeable when new, untradeable once equipped
    id: 'elite_malevolent_cuirass',
    name: 'Elite malevolent cuirass',
    tier: 92, style: 'melee', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Elite malevolent cuirass'),
    icon_url: img('Elite_malevolent_cuirass.png'),
    untradeable: 0,
    requirements_json: { Defence: 92 },
  },
  {
    // T92 ranged; tradeable when new
    id: 'elite_sirenic_hauberk',
    name: 'Elite sirenic hauberk',
    tier: 92, style: 'ranged', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Elite sirenic hauberk'),
    icon_url: img('Elite_sirenic_hauberk.png'),
    untradeable: 0,
    requirements_json: { Defence: 92 },
  },
  {
    // T92 magic; tradeable when new, untradeable once equipped
    id: 'elite_tectonic_robe_top',
    name: 'Elite tectonic robe top',
    tier: 92, style: 'magic', slot: 'body',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Elite tectonic robe top'),
    icon_url: img('Elite_tectonic_robe_top.png'),
    untradeable: 0,
    requirements_json: { Defence: 92 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // LEGS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'anima_core_legs_of_seren',
    name: 'Anima core legs of Seren',
    tier: 80, style: 'magic', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core legs of Seren'),
    icon_url: img('Anima_core_legs_of_Seren.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'anima_core_legs_of_zamorak',
    name: 'Anima core legs of Zamorak',
    tier: 80, style: 'ranged', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core legs of Zamorak'),
    icon_url: img('Anima_core_legs_of_Zamorak.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'anima_core_legs_of_zaros',
    name: 'Anima core legs of Zaros',
    tier: 80, style: 'melee', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Anima core legs of Zaros'),
    icon_url: img('Anima_core_legs_of_Zaros.png'),
    untradeable: 0,
    requirements_json: { Defence: 80 },
  },
  {
    id: 'rune_platelegs',
    name: 'Rune platelegs',
    tier: 50, style: 'melee', slot: 'legs',
    is_power_armour: 0,
    acquisition_source: 'ge',
    wiki_url: wikiUrl('Rune platelegs'),
    icon_url: img('Rune_platelegs.png'),
    untradeable: 0,
    requirements_json: { Defence: 50 },
  },
  {
    // Untradeable — Void Knight equipment
    id: 'void_ranger_robe',
    name: 'Void ranger robe',
    tier: 42, style: 'ranged', slot: 'legs',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Void ranger robe'),
    icon_url: img('Void_ranger_robe.png'),
    untradeable: 1,
    requirements_json: VOID,
  },
  {
    id: 'deathdealer_robe_bottom_t70',
    name: 'Deathdealer robe bottom (T70)',
    tier: 70, style: 'necromancy', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_robe_bottom_(tier_70)',
    icon_url: img('Deathdealer_robe_bottom_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70, Defence: 70 },
  },
  {
    id: 'deathdealer_robe_bottom_t80',
    name: 'Deathdealer robe bottom (T80)',
    tier: 80, style: 'necromancy', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_robe_bottom_(tier_80)',
    icon_url: img('Deathdealer_robe_bottom_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80, Defence: 80 },
  },
  {
    // Wiki article is "Cryptbloom bottoms" (plural) — image filename matches
    id: 'cryptbloom_bottom',
    name: 'Cryptbloom bottom',
    tier: 90, style: 'necromancy', slot: 'legs',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Cryptbloom bottoms'),
    icon_url: img('Cryptbloom_bottoms.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90, Defence: 90 },
  },
  {
    id: 'robe_bottom_of_the_first_necromancer',
    name: 'Robe bottom of the First Necromancer',
    tier: 95, style: 'necromancy', slot: 'legs',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Robe bottom of the First Necromancer'),
    icon_url: img('Robe_bottom_of_the_First_Necromancer.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 95 },
  },
  {
    id: 'elite_malevolent_greaves',
    name: 'Elite malevolent greaves',
    tier: 92, style: 'melee', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Elite malevolent greaves'),
    icon_url: img('Elite_malevolent_greaves.png'),
    untradeable: 0,
    requirements_json: { Defence: 92 },
  },
  {
    id: 'elite_sirenic_chaps',
    name: 'Elite sirenic chaps',
    tier: 92, style: 'ranged', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Elite sirenic chaps'),
    icon_url: img('Elite_sirenic_chaps.png'),
    untradeable: 0,
    requirements_json: { Defence: 92 },
  },
  {
    id: 'elite_tectonic_robe_bottom',
    name: 'Elite tectonic robe bottom',
    tier: 92, style: 'magic', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Elite tectonic robe bottom'),
    icon_url: img('Elite_tectonic_robe_bottom.png'),
    untradeable: 0,
    requirements_json: { Defence: 92 },
  },
  {
    // NOTE: seedRs3Data.js has "Virtus robe legs" (id: virtus_robe_legs).
    // GEAR_SUGGESTIONS.js references "Virtus robe bottom". Adding separate entry.
    id: 'virtus_robe_bottom',
    name: 'Virtus robe bottom',
    tier: 80, style: 'magic', slot: 'legs',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Virtus robe legs'),
    icon_url: img('Virtus_robe_legs.png'),
    untradeable: 0,
    requirements_json: { Defence: 80, Constitution: 80 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // GLOVES
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'armadyl_gloves',
    name: 'Armadyl gloves',
    tier: 70, style: 'ranged', slot: 'gloves',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Armadyl gloves'),
    icon_url: img('Armadyl_gloves.png'),
    untradeable: 0,
    requirements_json: { Defence: 70 },
  },
  {
    id: 'dragon_gauntlets',
    name: 'Dragon gauntlets',
    tier: 60, style: 'melee', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Dragon gauntlets'),
    icon_url: img('Dragon_gauntlets.png'),
    untradeable: 0,
    requirements_json: { Defence: 60 },
  },
  {
    id: 'pneumatic_gloves',
    name: 'Pneumatic gloves',
    tier: 85, style: 'ranged', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Pneumatic gloves'),
    icon_url: img('Pneumatic_gloves.png'),
    untradeable: 0,
    requirements_json: { Defence: 85 },
  },
  {
    id: 'static_gloves',
    name: 'Static gloves',
    tier: 85, style: 'magic', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Static gloves'),
    icon_url: img('Static_gloves.png'),
    untradeable: 0,
    requirements_json: { Defence: 85 },
  },
  {
    id: 'tracking_gloves',
    name: 'Tracking gloves',
    tier: 85, style: 'melee', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Tracking gloves'),
    icon_url: img('Tracking_gloves.png'),
    untradeable: 0,
    requirements_json: { Defence: 85 },
  },
  {
    // Untradeable — Void Knight equipment
    id: 'void_gloves',
    name: 'Void gloves',
    tier: 42, style: 'all', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Void gloves'),
    icon_url: img('Void_gloves.png'),
    untradeable: 1,
    requirements_json: VOID,
  },
  {
    id: 'deathdealer_gloves_t70',
    name: 'Deathdealer gloves (T70)',
    tier: 70, style: 'necromancy', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_gloves_(tier_70)',
    icon_url: img('Deathdealer_gloves_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70 },
  },
  {
    id: 'deathdealer_gloves_t80',
    name: 'Deathdealer gloves (T80)',
    tier: 80, style: 'necromancy', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_gloves_(tier_80)',
    icon_url: img('Deathdealer_gloves_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80 },
  },
  {
    id: 'deathdealer_gloves_t90',
    name: 'Deathdealer gloves (T90)',
    tier: 90, style: 'necromancy', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_gloves_(tier_90)',
    icon_url: img('Deathdealer_gloves_(tier_90).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90 },
  },
  {
    id: 'cryptbloom_gloves',
    name: 'Cryptbloom gloves',
    tier: 90, style: 'necromancy', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Cryptbloom gloves'),
    icon_url: img('Cryptbloom_gloves.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90 },
  },
  {
    // Wiki article uses "Hand wrap of the First Necromancer" (singular) for the image
    id: 'hand_wraps_of_the_first_necromancer',
    name: 'Hand wraps of the First Necromancer',
    tier: 95, style: 'necromancy', slot: 'gloves',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Hand wraps of the First Necromancer'),
    icon_url: img('Hand_wrap_of_the_First_Necromancer.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 95 },
  },
  {
    id: 'virtus_gloves',
    name: 'Virtus gloves',
    tier: 80, style: 'magic', slot: 'gloves',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Virtus gloves'),
    icon_url: img('Virtus_gloves.png'),
    untradeable: 0,
    requirements_json: { Defence: 80, Constitution: 80 },
  },
  {
    id: 'pernix_gloves',
    name: 'Pernix gloves',
    tier: 80, style: 'ranged', slot: 'gloves',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Pernix gloves'),
    icon_url: img('Pernix_gloves.png'),
    untradeable: 0,
    requirements_json: { Defence: 80, Constitution: 80 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BOOTS
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'armadyl_boots',
    name: 'Armadyl boots',
    tier: 70, style: 'ranged', slot: 'boots',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Armadyl boots'),
    icon_url: img('Armadyl_boots.png'),
    untradeable: 0,
    requirements_json: { Defence: 70 },
  },
  {
    // T90; tradeable when new, untradeable once equipped
    id: 'flarefrost_boots',
    name: 'Flarefrost boots',
    tier: 90, style: 'ranged', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Flarefrost boots'),
    icon_url: img('Flarefrost_boots.png'),
    untradeable: 0, // tradeable when new
    requirements_json: { Defence: 90 },
  },
  {
    id: 'infinity_boots',
    name: 'Infinity boots',
    tier: 50, style: 'magic', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Infinity boots'),
    icon_url: img('Infinity_boots.png'),
    untradeable: 0,
    requirements_json: { Magic: 50, Defence: 55 },
  },
  {
    id: 'pernix_boots',
    name: 'Pernix boots',
    tier: 80, style: 'ranged', slot: 'boots',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Pernix boots'),
    icon_url: img('Pernix_boots.png'),
    untradeable: 0,
    requirements_json: { Defence: 80, Constitution: 80 },
  },
  {
    id: 'ranger_boots',
    name: 'Ranger boots',
    tier: 40, style: 'ranged', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Ranger boots'),
    icon_url: img('Ranger_boots.png'),
    untradeable: 0,
    requirements_json: { Ranged: 40 },
  },
  {
    id: 'rune_boots',
    name: 'Rune boots',
    tier: 50, style: 'melee', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Rune boots'),
    icon_url: img('Rune_boots.png'),
    untradeable: 0,
    requirements_json: { Defence: 50 },
  },
  {
    id: 'tectonic_boots',
    name: 'Tectonic boots',
    tier: 90, style: 'magic', slot: 'boots',
    is_power_armour: 1,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Tectonic boots'),
    icon_url: img('Tectonic_boots.png'),
    untradeable: 0,
    requirements_json: { Defence: 90 },
  },
  {
    id: 'virtus_boots',
    name: 'Virtus boots',
    tier: 80, style: 'magic', slot: 'boots',
    is_power_armour: 1,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Virtus boots'),
    icon_url: img('Virtus_boots.png'),
    untradeable: 0,
    requirements_json: { Defence: 80, Constitution: 80 },
  },
  {
    id: 'deathdealer_boots_t70',
    name: 'Deathdealer boots (T70)',
    tier: 70, style: 'necromancy', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_boots_(tier_70)',
    icon_url: img('Deathdealer_boots_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70 },
  },
  {
    id: 'deathdealer_boots_t80',
    name: 'Deathdealer boots (T80)',
    tier: 80, style: 'necromancy', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_boots_(tier_80)',
    icon_url: img('Deathdealer_boots_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80 },
  },
  {
    id: 'deathdealer_boots_t90',
    name: 'Deathdealer boots (T90)',
    tier: 90, style: 'necromancy', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Deathdealer_boots_(tier_90)',
    icon_url: img('Deathdealer_boots_(tier_90).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90 },
  },
  {
    id: 'cryptbloom_boots',
    name: 'Cryptbloom boots',
    tier: 90, style: 'necromancy', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Cryptbloom boots'),
    icon_url: img('Cryptbloom_boots.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90 },
  },
  {
    id: 'foot_wraps_of_the_first_necromancer',
    name: 'Foot wraps of the First Necromancer',
    tier: 95, style: 'necromancy', slot: 'boots',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Foot wraps of the First Necromancer'),
    icon_url: img('Foot_wraps_of_the_First_Necromancer.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 95 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // RING
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'onyx_ring_i',
    name: 'Onyx ring (i)',
    tier: 70, style: 'all', slot: 'ring',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Onyx ring (i)'),
    icon_url: img('Onyx_ring_(i).png'),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Wiki calls this "Occultist's ring" — "Seal of the Occultist" is an alternate name
    id: 'seal_of_the_occultist',
    name: 'Seal of the Occultist',
    tier: 0, style: 'necromancy', slot: 'ring',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: "https://runescape.wiki/w/Occultist%27s_ring",
    icon_url: img("Occultist%27s_ring.png"),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Untradeable — quest reward from The World Wakes
    id: 'sixth_age_circuit',
    name: 'Sixth-Age circuit',
    tier: 0, style: 'all', slot: 'ring',
    is_power_armour: 0,
    acquisition_source: 'quest',
    wiki_url: wikiUrl('Sixth-Age circuit'),
    icon_url: img('Sixth-Age_circuit.png'),
    untradeable: 1,
    requirements_json: {},
  },

  // ══════════════════════════════════════════════════════════════════════════
  // CAPE
  // ══════════════════════════════════════════════════════════════════════════

  {
    // Trimmed skill capes are tradeable on GE
    id: 'attack_cape_t',
    name: 'Attack cape (t)',
    tier: 0, style: 'melee', slot: 'cape',
    is_power_armour: 0,
    acquisition_source: 'achievement',
    wiki_url: wikiUrl('Attack cape (t)'),
    icon_url: img('Attack_cape_(t).png'),
    untradeable: 0,
    requirements_json: { Attack: 99 },
  },
  {
    id: 'magic_cape_t',
    name: 'Magic cape (t)',
    tier: 0, style: 'magic', slot: 'cape',
    is_power_armour: 0,
    acquisition_source: 'achievement',
    wiki_url: wikiUrl('Magic cape (t)'),
    icon_url: img('Magic_cape_(t).png'),
    untradeable: 0,
    requirements_json: { Magic: 99 },
  },
  {
    id: 'necromancy_cape_t',
    name: 'Necromancy cape (t)',
    tier: 0, style: 'necromancy', slot: 'cape',
    is_power_armour: 0,
    acquisition_source: 'achievement',
    wiki_url: wikiUrl('Necromancy cape (t)'),
    icon_url: img('Necromancy_cape_(t).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 99 },
  },
  {
    id: 'ranging_cape_t',
    name: 'Ranging cape (t)',
    tier: 0, style: 'ranged', slot: 'cape',
    is_power_armour: 0,
    acquisition_source: 'achievement',
    wiki_url: wikiUrl('Ranging cape (t)'),
    icon_url: img('Ranging_cape_(t).png'),
    untradeable: 0,
    requirements_json: { Ranged: 99 },
  },
  {
    id: 'strength_cape_t',
    name: 'Strength cape (t)',
    tier: 0, style: 'melee', slot: 'cape',
    is_power_armour: 0,
    acquisition_source: 'achievement',
    wiki_url: wikiUrl('Strength cape (t)'),
    icon_url: img('Strength_cape_(t).png'),
    untradeable: 0,
    requirements_json: { Strength: 99 },
  },
  {
    // Untradeable — Fight Kiln reward (Necromancy style)
    id: 'tokhaar_kal_mor',
    name: 'TokHaar-Kal-Mor',
    tier: 80, style: 'necromancy', slot: 'cape',
    is_power_armour: 0,
    acquisition_source: 'boss',
    wiki_url: wikiUrl('TokHaar-Kal-Mor'),
    icon_url: img('TokHaar-Kal-Mor.png'),
    untradeable: 1,
    requirements_json: {},
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEAPON
  // ══════════════════════════════════════════════════════════════════════════

  {
    // "Blade of Nymora + Avaryss" is the dual-wield entry in GEAR_SUGGESTIONS.
    // The individual blade is already seeded (id: blade_of_nymora).
    // This entry represents the dual-wield pair as it appears in suggestions.
    id: 'blade_of_nymora_avaryss',
    name: 'Blade of Nymora + Avaryss',
    tier: 85, style: 'melee', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Blade of Nymora'),
    icon_url: img('Blade_of_Nymora.png'),
    untradeable: 0,
    requirements_json: { Attack: 85 },
  },
  {
    id: 'crystal_bow',
    name: 'Crystal bow',
    tier: 70, style: 'ranged', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'quest',
    wiki_url: wikiUrl('Crystal bow'),
    icon_url: img('Crystal_bow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 70, Agility: 50 },
  },
  {
    id: 'crystal_wand',
    name: 'Crystal wand',
    tier: 70, style: 'magic', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'quest',
    wiki_url: wikiUrl('Crystal wand'),
    icon_url: img('Crystal_wand.png'),
    untradeable: 0,
    requirements_json: { Magic: 70, Agility: 50 },
  },
  {
    id: 'decimation',
    name: 'Decimation',
    tier: 87, style: 'ranged', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Decimation'),
    icon_url: img('Decimation.png'),
    untradeable: 0,
    requirements_json: { Ranged: 87 },
  },
  {
    // Already seeded in seedRs3Data.js (id: dragon_2h_sword) but icon_url may be NULL.
    // This upsert patches it to have the correct icon_url.
    id: 'dragon_2h_sword',
    name: 'Dragon 2H sword',
    tier: 60, style: 'melee', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Dragon 2H sword'),
    icon_url: img('Dragon_2H_sword.png'),
    untradeable: 0,
    requirements_json: { Attack: 60 },
  },
  {
    // Dual drygore longswords — represents the main-hand + off-hand pair in suggestions
    id: 'dual_drygore_longswords',
    name: 'Dual drygore longswords',
    tier: 90, style: 'melee', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Drygore longsword'),
    icon_url: img('Drygore_longsword.png'),
    untradeable: 0,
    requirements_json: { Attack: 90 },
  },
  {
    id: 'dual_drygore_maces',
    name: 'Dual drygore maces',
    tier: 90, style: 'melee', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Drygore mace'),
    icon_url: img('Drygore_mace.png'),
    untradeable: 0,
    requirements_json: { Attack: 90 },
  },
  {
    id: 'dual_drygore_rapiers',
    name: 'Dual drygore rapiers',
    tier: 90, style: 'melee', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Drygore rapier'),
    icon_url: img('Drygore_rapier.png'),
    untradeable: 0,
    requirements_json: { Attack: 90 },
  },
  {
    // "Ascension crossbow + off-hand" represents the dual-wield pair
    id: 'ascension_crossbow_dual',
    name: 'Ascension crossbow + off-hand',
    tier: 90, style: 'ranged', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Ascension crossbow'),
    icon_url: img('Ascension_crossbow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 90 },
  },
  {
    // "Blightbound crossbow + off-hand" represents the dual-wield pair
    id: 'blightbound_crossbow_dual',
    name: 'Blightbound crossbow + off-hand',
    tier: 92, style: 'ranged', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Blightbound crossbow'),
    icon_url: img('Blightbound_crossbow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 92 },
  },
  {
    id: 'master_wand',
    name: 'Master wand',
    tier: 70, style: 'magic', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'minigame',
    wiki_url: wikiUrl('Master wand'),
    icon_url: img('Master_wand.png'),
    untradeable: 0,
    requirements_json: { Magic: 70 },
  },
  {
    id: 'obliteration',
    name: 'Obliteration',
    tier: 87, style: 'magic', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Obliteration'),
    icon_url: img('Obliteration.png'),
    untradeable: 0,
    requirements_json: { Magic: 87 },
  },
  {
    id: 'rune_crossbow',
    name: 'Rune crossbow',
    tier: 65, style: 'ranged', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'ge',
    wiki_url: wikiUrl('Rune crossbow'),
    icon_url: img('Rune_crossbow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 65 },
  },
  {
    id: 'shadow_glaive',
    name: 'Shadow glaive',
    tier: 85, style: 'ranged', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Shadow glaive'),
    icon_url: img('Shadow_glaive.png'),
    untradeable: 0,
    requirements_json: { Ranged: 85 },
  },
  {
    id: 'staff_of_light',
    name: 'Staff of light',
    tier: 75, style: 'magic', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Staff of light'),
    icon_url: img('Staff_of_light.png'),
    untradeable: 0,
    requirements_json: { Magic: 75 },
  },
  {
    id: 'death_guard_t60',
    name: 'Death Guard (T60)',
    tier: 60, style: 'necromancy', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Death_guard_(tier_60)',
    icon_url: img('Death_guard_(tier_60).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 60 },
  },
  {
    id: 'death_guard_t70',
    name: 'Death Guard (T70)',
    tier: 70, style: 'necromancy', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Death_guard_(tier_70)',
    icon_url: img('Death_guard_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70 },
  },
  {
    id: 'death_guard_t80',
    name: 'Death Guard (T80)',
    tier: 80, style: 'necromancy', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Death_guard_(tier_80)',
    icon_url: img('Death_guard_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80 },
  },
  {
    id: 'death_guard_t90',
    name: 'Death Guard (T90)',
    tier: 90, style: 'necromancy', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Death_guard_(tier_90)',
    icon_url: img('Death_guard_(tier_90).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90 },
  },
  {
    // T95 Necromancy main-hand; tradeable when new
    id: 'omni_guard',
    name: 'Omni Guard',
    tier: 95, style: 'necromancy', slot: 'weapon',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Omni guard'),
    icon_url: img('Omni_guard.png'),
    untradeable: 0,
    requirements_json: { Necromancy: 95 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // OFFHAND
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'dragon_kiteshield',
    name: 'Dragon kiteshield',
    tier: 60, style: 'melee', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Dragon kiteshield'),
    icon_url: img('Dragon_kiteshield.png'),
    untradeable: 0,
    requirements_json: { Defence: 60 },
  },
  {
    id: 'dragonfire_shield',
    name: 'Dragonfire shield',
    tier: 75, style: 'melee', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Dragonfire shield'),
    icon_url: img('Dragonfire_shield.png'),
    untradeable: 0,
    requirements_json: { Defence: 75 },
  },
  {
    id: 'merciless_kiteshield',
    name: 'Merciless kiteshield',
    tier: 90, style: 'ranged', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Merciless kiteshield'),
    icon_url: img('Merciless_kiteshield.png'),
    untradeable: 0,
    requirements_json: { Defence: 75 },
  },
  {
    // wiki: "Off-hand Blightbound crossbow" (capital B in filename)
    id: 'oh_blightbound_crossbow',
    name: 'Off-hand blightbound crossbow',
    tier: 92, style: 'ranged', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Off-hand blightbound crossbow'),
    icon_url: img('Off-hand_Blightbound_crossbow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 92 },
  },
  {
    // Untradeable — Dungeoneering reward
    id: 'oh_chaotic_crossbow',
    name: 'Off-hand chaotic crossbow',
    tier: 80, style: 'ranged', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'dungeoneering',
    wiki_url: wikiUrl('Off-hand chaotic crossbow'),
    icon_url: img('Off-hand_chaotic_crossbow.png'),
    untradeable: 1,
    requirements_json: { Ranged: 80, Dungeoneering: 80 },
  },
  {
    id: 'skull_lantern_t60',
    name: 'Skull Lantern (T60)',
    tier: 60, style: 'necromancy', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Skull_lantern_(tier_60)',
    icon_url: img('Skull_lantern_(tier_60).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 60 },
  },
  {
    id: 'skull_lantern_t70',
    name: 'Skull Lantern (T70)',
    tier: 70, style: 'necromancy', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Skull_lantern_(tier_70)',
    icon_url: img('Skull_lantern_(tier_70).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 70 },
  },
  {
    id: 'skull_lantern_t80',
    name: 'Skull Lantern (T80)',
    tier: 80, style: 'necromancy', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Skull_lantern_(tier_80)',
    icon_url: img('Skull_lantern_(tier_80).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 80 },
  },
  {
    id: 'skull_lantern_t90',
    name: 'Skull Lantern (T90)',
    tier: 90, style: 'necromancy', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: 'https://runescape.wiki/w/Skull_lantern_(tier_90)',
    icon_url: img('Skull_lantern_(tier_90).png'),
    untradeable: 0,
    requirements_json: { Necromancy: 90 },
  },
  {
    // Already seeded (id: soulbound_lantern) but icon_url may be NULL — patching it
    id: 'soulbound_lantern',
    name: 'Soulbound Lantern',
    tier: 95, style: 'necromancy', slot: 'offhand',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Soulbound lantern'),
    icon_url: img('Soulbound_lantern.png'),
    untradeable: 0, // tradeable when new (undyed)
    requirements_json: { Necromancy: 95 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // AMMO
  // ══════════════════════════════════════════════════════════════════════════

  {
    // Wiki uses the singular "Araxyte arrow" as the image name
    id: 'araxyte_arrows',
    name: 'Araxyte arrows',
    tier: 90, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Araxyte arrow'),
    icon_url: img('Araxyte_arrow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 90 },
  },
  {
    id: 'ascension_bolts',
    name: 'Ascension bolts',
    tier: 90, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Ascension bolts'),
    icon_url: img('Ascension_bolts.png'),
    untradeable: 0,
    requirements_json: { Ranged: 90 },
  },
  {
    id: 'broad_tipped_bolts',
    name: 'Broad-tipped bolts',
    tier: 55, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'slayer',
    wiki_url: wikiUrl('Broad-tipped bolts'),
    icon_url: img('Broad-tipped_bolts.png'),
    untradeable: 0,
    requirements_json: { Ranged: 55 },
  },
  {
    id: 'diamond_bakriminel_bolts_e',
    name: 'Diamond bakriminel bolts (e)',
    tier: 80, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Diamond bakriminel bolts (e)'),
    icon_url: img('Diamond_bakriminel_bolts_(e).png'),
    untradeable: 0,
    requirements_json: { Ranged: 80 },
  },
  {
    id: 'dragon_arrows',
    name: 'Dragon arrows',
    tier: 60, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'drop',
    wiki_url: wikiUrl('Dragon arrow'),
    icon_url: img('Dragon_arrow.png'),
    untradeable: 0,
    requirements_json: { Ranged: 60 },
  },
  {
    id: 'dragonstone_bakriminel_bolts_e',
    name: 'Dragonstone bakriminel bolts (e)',
    tier: 80, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Dragonstone bakriminel bolts (e)'),
    icon_url: img('Dragonstone_bakriminel_bolts_(e).png'),
    untradeable: 0,
    requirements_json: { Ranged: 80 },
  },
  {
    id: 'hydrix_bakriminel_bolts_e',
    name: 'Hydrix bakriminel bolts (e)',
    tier: 80, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Hydrix bakriminel bolts (e)'),
    icon_url: img('Hydrix_bakriminel_bolts_(e).png'),
    untradeable: 0,
    requirements_json: { Ranged: 80 },
  },
  {
    id: 'onyx_bakriminel_bolts_e',
    name: 'Onyx bakriminel bolts (e)',
    tier: 80, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Onyx bakriminel bolts (e)'),
    icon_url: img('Onyx_bakriminel_bolts_(e).png'),
    untradeable: 0,
    requirements_json: { Ranged: 80 },
  },
  {
    id: 'ruby_bakriminel_bolts_e',
    name: 'Ruby bakriminel bolts (e)',
    tier: 80, style: 'ranged', slot: 'ammo',
    is_power_armour: 0,
    acquisition_source: 'crafting',
    wiki_url: wikiUrl('Ruby bakriminel bolts (e)'),
    icon_url: img('Ruby_bakriminel_bolts_(e).png'),
    untradeable: 0,
    requirements_json: { Ranged: 80 },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // POCKET
  // ══════════════════════════════════════════════════════════════════════════

  {
    // "God book (any)" — using Saradomin's book as the representative image
    id: 'god_book_any',
    name: 'God book (any)',
    tier: 0, style: 'all', slot: 'pocket',
    is_power_armour: 0,
    acquisition_source: 'quest',
    wiki_url: wikiUrl('God book'),
    icon_url: img('God_book_(Saradomin).png'),
    untradeable: 0,
    requirements_json: {},
  },
  {
    // Untradeable — made by illuminating a god book (Horror from the Deep)
    id: 'illuminated_god_book',
    name: 'Illuminated god book',
    tier: 0, style: 'all', slot: 'pocket',
    is_power_armour: 0,
    acquisition_source: 'quest',
    wiki_url: wikiUrl('Illuminated god book'),
    icon_url: img('Illuminated_Book_of_Law.png'),
    untradeable: 1,
    requirements_json: {},
  },
  {
    id: 'scripture_of_ful',
    name: 'Scripture of Ful',
    tier: 0, style: 'necromancy', slot: 'pocket',
    is_power_armour: 0,
    acquisition_source: 'ge',
    wiki_url: wikiUrl('Scripture of Ful'),
    icon_url: img('Scripture_of_Ful.png'),
    untradeable: 0,
    requirements_json: {},
  },

];

// ── Run upserts ───────────────────────────────────────────────────────────────
let added = 0, updated = 0;
for (const item of ITEMS) {
  const existing = db.prepare('SELECT id FROM rs3_gear_items WHERE id = ?').get(item.id);
  upsertItem(item);
  if (existing) updated++; else added++;
}

console.log(`Done: ${added} added, ${updated} updated.`);
console.log(`Total gear items: ${db.prepare('SELECT COUNT(*) as n FROM rs3_gear_items').get().n}`);
